apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: {{.Values.frontName}}
  name: {{.Values.frontName}}
  namespace: {{.Values.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{.Values.frontName}}
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/charts-default: "true"
        io.kompose.service: {{.Values.frontName}}
    spec:
      containers:
        - image: "{{.Values.image.user}}{{.Values.image.nameFront}}:{{.Values.image.tagFront}}"
          name: {{.Values.frontContainerName}}
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: {{.Values.frontName}}
  name: {{.Values.frontName}}
  namespace: {{.Values.Namespace}}
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: {{.Values.frontName}}
status:
  loadBalancer: {}
