version: '3.9'

services:
  frontend: # Name of our service
    build: ../Front # path to dockerfile
    ports: # Port binding to host from docker container
      - "8081:8081" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend
    volumes: 
      - ../Front/:/usr/src/app
      - /usr/src/app/node_modules
    environment: 
    - CHOKIDAR_USEPOLLING=true
    tty: true

  backend:
    build: ../Back
    ports: 
      - "8080:8080"
      - "9229:9229"
    container_name: backend-docker
    restart: always
    volumes: 
      - ../Back/:/usr/src/app
      - ignore:/usr/src/app/node_modules
    environment: 
    - NODE_ENV=development
    - CHOKIDAR_USEPOLLING=true
    command: 
      - nodemon 
      - --inspect=0.0.0.0:9229
      - index.js
    tty: true
    # links: 
    #   - db

volumes:
  ignore:
  # db:
  #   image: postgres:11.6-alpine
  #   ports: 
  #     - "5432:5432"
  #   container_name: database-docker
  #   restart: always