apiVersion: v1
kind: Service
metadata:
  name: default-prometheus-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: default-prometheus
  ports:
    - name: web
      port: 9090
      targetPort: 9090
      nodePort: 30000
  externalIPs:
    - 10.0.0.100